# Generated by Django 6.0.3 on 2026-05-13 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_criacao', models.DateTimeField(null=True)),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Série'), (2, 'Filme')])),
                ('categorias', models.ManyToManyField(to='app.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ordem', models.IntegerField()),
                ('nome', models.CharField()),
                ('descricao', models.TextField()),
                ('numero', models.IntegerField()),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.midia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ordem', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField()),
                ('descricao', models.TextField()),
                ('duracao', models.IntegerField()),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.temporada')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
